(let ([n 5])
  (let ([a 0])
    (let ([b 1])
      (let ([i 0])
        (let ([result (if (eq? n 0) 
                          a
                          (if (eq? n 1)
                              b
                              (let ([i 1])
                                (let ([loop 
                                      (if (< i n)
                                          (let ([c (+ a b)])
                                            (let ([a b])
                                              (let ([b c])
                                                (let ([i (+ i 1)])
                                                  (if (< i n)
                                                      (let ([c (+ a b)])
                                                        (let ([a b])
                                                          (let ([b c])
                                                            (let ([i (+ i 1)])
                                                              (if (< i n)
                                                                  (let ([c (+ a b)])
                                                                    (let ([a b])
                                                                      (let ([b c])
                                                                        (let ([i (+ i 1)])
                                                                          (if (< i n)
                                                                              (let ([c (+ a b)])
                                                                                (let ([a b])
                                                                                  (let ([b c])
                                                                                    b)))
                                                                              b)))))
                                                                  b)))))
                                                      b)))))
                                          b)])
                                  loop))))])
          result)))))