(let ([x (read)])
  (let ([x (+ x x)])
    (let ([x (+ x x)])
      (let ([x (+ x x)])
        (let ([x (+ x x)])
          (let ([x (+ x x)])
            (let ([x (+ x x)])
              (let ([x (+ x x)])
                (let ([x (+ x x)])
                  (let ([x (+ x x)])
                    x))))))))))